{% set name = "cachelib" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cachelib-{{ version }}.tar.gz
  sha256: 292e89d5f9201fb9570e9f222c202f59085c66f9cb8bdfeefcfffff2b442fb2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - cachelib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pallets-eco/cachelib
  summary: A collection of cache libraries in the same API interface.
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - fuglede
